-- CreateTable
CREATE TABLE `Admin` (
    `Admin_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `User_ID` INTEGER NOT NULL,

    UNIQUE INDEX `User_ID`(`User_ID`),
    PRIMARY KEY (`Admin_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `COURSES` (
    `Course_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Course_Number` INTEGER NULL,
    `Course_Section` DECIMAL(4, 1) NULL,
    `Course_Title` VARCHAR(255) NULL,
    `Course_Instructor` VARCHAR(255) NULL,
    `Enrolled_Count` INTEGER NULL DEFAULT 0,

    PRIMARY KEY (`Course_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ENROLLMENTS` (
    `Enrollment_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `User_ID` INTEGER NOT NULL,
    `Tutor_ID` INTEGER NULL,
    `Course_ID` INTEGER NOT NULL,
    `Total_Enrollment` INTEGER NULL DEFAULT 0,

    INDEX `Course_ID`(`Course_ID`),
    INDEX `Tutor_ID`(`Tutor_ID`),
    INDEX `User_ID`(`User_ID`),
    PRIMARY KEY (`Enrollment_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SCHEDULE` (
    `Schedule_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Admin_ID` INTEGER NOT NULL,
    `Availability_ID` INTEGER NOT NULL,
    `Has_Worked` BOOLEAN NULL DEFAULT false,

    INDEX `Admin_ID`(`Admin_ID`),
    INDEX `Availability_ID`(`Availability_ID`),
    PRIMARY KEY (`Schedule_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STUDY_BUDDY_GROUPS` (
    `Group_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `User_ID` INTEGER NOT NULL,
    `Tutor_ID` INTEGER NULL,
    `Enrollment_ID` INTEGER NOT NULL,
    `Is_Accepted` BOOLEAN NULL DEFAULT false,
    `Has_Tutor` BOOLEAN NULL DEFAULT false,
    `Group_Members` INTEGER NULL DEFAULT 0,

    INDEX `Enrollment_ID`(`Enrollment_ID`),
    INDEX `Tutor_ID`(`Tutor_ID`),
    INDEX `User_ID`(`User_ID`),
    PRIMARY KEY (`Group_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STUDY_GROUP_MEMBERS` (
    `Member_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Group_ID` INTEGER NOT NULL,
    `User_ID` INTEGER NOT NULL,
    `Enrollment_ID` INTEGER NOT NULL,

    INDEX `STUDY_GROUP_MEMBERS_Group_ID_idx`(`Group_ID`),
    INDEX `STUDY_GROUP_MEMBERS_User_ID_idx`(`User_ID`),
    INDEX `STUDY_GROUP_MEMBERS_Enrollment_ID_idx`(`Enrollment_ID`),
    UNIQUE INDEX `STUDY_GROUP_MEMBERS_Group_ID_User_ID_key`(`Group_ID`, `User_ID`),
    PRIMARY KEY (`Member_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Student` (
    `User_ID` INTEGER NOT NULL,
    `GPA` DECIMAL(4, 3) NULL,

    PRIMARY KEY (`User_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TUTORING_SESSION` (
    `Session_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `User_ID` INTEGER NOT NULL,
    `Tutor_ID` INTEGER NOT NULL,
    `Enrollment_ID` INTEGER NOT NULL,
    `Session_Date` DATE NULL,
    `Session_Time` TIMESTAMP(0) NULL,
    `Session_Loc` VARCHAR(255) NULL,
    `Students_Booked` INTEGER NULL DEFAULT 0,
    `Session_Max` INTEGER NULL DEFAULT 0,

    INDEX `Enrollment_ID`(`Enrollment_ID`),
    INDEX `Tutor_ID`(`Tutor_ID`),
    INDEX `User_ID`(`User_ID`),
    PRIMARY KEY (`Session_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TUTOR_AVAILABILITY` (
    `Availability_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Tutor_ID` INTEGER NOT NULL,
    `Date_Requested` DATE NULL,
    `Is_Approved` BOOLEAN NULL DEFAULT false,
    `Times_Requested` TIMESTAMP(0) NULL,

    INDEX `Tutor_ID`(`Tutor_ID`),
    PRIMARY KEY (`Availability_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Tutor` (
    `Tutor_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `User_ID` INTEGER NOT NULL,

    UNIQUE INDEX `User_ID`(`User_ID`),
    PRIMARY KEY (`Tutor_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USERS` (
    `User_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(255) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    `Is_Admin` BOOLEAN NULL DEFAULT false,
    `Is_Tutor` BOOLEAN NULL DEFAULT false,
    `Is_Student` BOOLEAN NULL DEFAULT true,

    UNIQUE INDEX `Email`(`Email`),
    PRIMARY KEY (`User_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TUTOR_COURSE` (
    `TutorCourseID` INTEGER NOT NULL AUTO_INCREMENT,
    `Tutor_ID` INTEGER NOT NULL,
    `Course_ID` INTEGER NOT NULL,

    INDEX `Course_ID`(`Course_ID`),
    INDEX `Tutor_ID`(`Tutor_ID`),
    PRIMARY KEY (`TutorCourseID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Admin` ADD CONSTRAINT `Admin_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENROLLMENTS` ADD CONSTRAINT `ENROLLMENTS_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENROLLMENTS` ADD CONSTRAINT `ENROLLMENTS_ibfk_2` FOREIGN KEY (`Tutor_ID`) REFERENCES `Tutor`(`Tutor_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ENROLLMENTS` ADD CONSTRAINT `ENROLLMENTS_ibfk_3` FOREIGN KEY (`Course_ID`) REFERENCES `COURSES`(`Course_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SCHEDULE` ADD CONSTRAINT `SCHEDULE_ibfk_1` FOREIGN KEY (`Admin_ID`) REFERENCES `Admin`(`Admin_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SCHEDULE` ADD CONSTRAINT `SCHEDULE_ibfk_2` FOREIGN KEY (`Availability_ID`) REFERENCES `TUTOR_AVAILABILITY`(`Availability_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDY_BUDDY_GROUPS` ADD CONSTRAINT `STUDY_BUDDY_GROUPS_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDY_BUDDY_GROUPS` ADD CONSTRAINT `STUDY_BUDDY_GROUPS_ibfk_2` FOREIGN KEY (`Tutor_ID`) REFERENCES `Tutor`(`Tutor_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDY_BUDDY_GROUPS` ADD CONSTRAINT `STUDY_BUDDY_GROUPS_ibfk_3` FOREIGN KEY (`Enrollment_ID`) REFERENCES `ENROLLMENTS`(`Enrollment_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDY_GROUP_MEMBERS` ADD CONSTRAINT `STUDY_GROUP_MEMBERS_Group_ID_fkey` FOREIGN KEY (`Group_ID`) REFERENCES `STUDY_BUDDY_GROUPS`(`Group_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDY_GROUP_MEMBERS` ADD CONSTRAINT `STUDY_GROUP_MEMBERS_User_ID_fkey` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDY_GROUP_MEMBERS` ADD CONSTRAINT `STUDY_GROUP_MEMBERS_Enrollment_ID_fkey` FOREIGN KEY (`Enrollment_ID`) REFERENCES `ENROLLMENTS`(`Enrollment_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Student` ADD CONSTRAINT `Student_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TUTORING_SESSION` ADD CONSTRAINT `TUTORING_SESSION_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TUTORING_SESSION` ADD CONSTRAINT `TUTORING_SESSION_ibfk_2` FOREIGN KEY (`Tutor_ID`) REFERENCES `Tutor`(`Tutor_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TUTORING_SESSION` ADD CONSTRAINT `TUTORING_SESSION_ibfk_3` FOREIGN KEY (`Enrollment_ID`) REFERENCES `ENROLLMENTS`(`Enrollment_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TUTOR_AVAILABILITY` ADD CONSTRAINT `TUTOR_AVAILABILITY_ibfk_1` FOREIGN KEY (`Tutor_ID`) REFERENCES `Tutor`(`Tutor_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Tutor` ADD CONSTRAINT `Tutor_ibfk_1` FOREIGN KEY (`User_ID`) REFERENCES `USERS`(`User_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TUTOR_COURSE` ADD CONSTRAINT `TUTOR_COURSE_ibfk_1` FOREIGN KEY (`Tutor_ID`) REFERENCES `Tutor`(`Tutor_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TUTOR_COURSE` ADD CONSTRAINT `TUTOR_COURSE_ibfk_2` FOREIGN KEY (`Course_ID`) REFERENCES `COURSES`(`Course_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
